### ISSUE TITLE
How to add multiple features?

### ISSUE THREAD

**Issue by janderz8** [raamana/neuropredict#10]
Hi Pradeep,

I can see the file structure for adding a single feature is: 

subject1/features.txt 
subject2/features.txt 
subject3/features.txt 
subject4/features.txt 

Where the feature is a vector in each case.  To clarify, if I wanted to add a second feature, would this be a second column in the features.txt file of each participant?

Thanks,

John

**Comment by raamana** [comment]
You want to create a parallel folder. 
Let's say you had one feature set in folder feature_one/:
```
feature_one/subject1/features.txt
feature_one/subject2/features.txt
feature_one/subject3/features.txt
feature_one/subject4/features.txt
```
You would want to create another folder feature_two:
```
feature_two/subject1/features.txt
feature_two/subject2/features.txt
feature_two/subject3/features.txt
feature_two/subject4/features.txt
```

and specify the two folder paths as multiple values for flag -u

`-u  /project/feature_one  /project/feature_two`

**Comment by janderz8** [comment]
Awesome :), thanks!  Running now

**Comment by raamana** [comment]
You want to name these top level folder appropriately, as they will be used to annotate the results. What kind of data are you using? and how long is neuropredict taking for each run?

**Comment by janderz8** [comment]
I'm examining subject scores from a two PLS analyses - one of vascular regions & a second of GM regions.  I've run each of these separately (~ 15 min), but haven't looked at them together.

**Comment by raamana** [comment]
A coffee break essentially :).. 15 mins has been typical in my experience also..

**Comment by raamana** [comment]
Glad to hear youre able to use it. Spread the word! :)

I need to get a DOI somewhere so users can cite it..

**Comment by janderz8** [comment]
Sounds good!  & I'm going to need to figure out how to report the results, so once I get through that, I may be able to help with documentation.

**Comment by raamana** [comment]
That'd be awsome, John. Your help, being a new user, will be helpful for others. I may even use it automate that process further to minimize work for people later on.

**Comment by raamana** [comment]
If predictive modeling is a non-trivial part of your study, I can help with completing the "analysis" and organizing reports as you need. If you just want to report some accuracy numbers and comparison, you probably wont need me.

**Comment by janderz8** [comment]
A reviewer argued that the PLS analysis we ran wasn't "novel enough", but that machine learning would be. Not trivial then.  I'll take a first crack at this & send to you for vetting if that's ok.   I want to make sure that what I say makes sense & accurately describes the results.
