### ISSUE TITLE
Implement versioneer to automate versioning and releases

### ISSUE THREAD

**Issue by raamana** [raamana/neuropredict#14]
Check https://github.com/warner/python-versioneer/blob/master/INSTALL.md

**Comment by kevinkle** [comment]
testing an implementation of this now. will pr it on oct. 1 :jack_o_lantern:

**Comment by raamana** [comment]
Thanks Kevin 👍

**Comment by raamana** [comment]
Hey Kevin, I had a chance to try something already - check the parallel_rhst branch for versioneer details.

when I tried running this:
```bash
python setup.py sdist bdist_wheel
twine upload dist/*
```

I get the following errors:
```
running install_egg_info
Copying neuropredict.egg-info to build/bdist.macosx-10.7-x86_64/wheel/neuropredict-0.3.1+1.g83a8126-py3.6.egg-info
running install_scripts
creating build/bdist.macosx-10.7-x86_64/wheel/neuropredict-0.3.1+1.g83a8126.dist-info/WHEEL
Uploading distributions to https://upload.pypi.org/legacy/
Uploading neuropredict-0.3.1+1.g83a8126-py3-none-any.whl
[================================] 42211/42211 - 00:00:00
HTTPError: 400 Client Error: version: Cannot use PEP 440 local versions. for url: https://upload.pypi.org/legacy/
```

any ideas? If you could help debug it, that would be great.

**Comment by kevinkle** [comment]
Hi Pradeep,

The `neuropredict-0.3.1+1.g83a8126-py3-none-any.whl` tag shows up because the tag is dirty - there are some updates to the .gitignore that need to be added.

```
 ❯ twine upload dist/*                                                                                                                                                                                                             [12:14:41]
Uploading distributions to https://upload.pypi.org/legacy/
Enter your username: kevinkle
Enter your password:
Uploading faberfase-0.0.5-py2-none-any.whl
Uploading faberfase-0.0.5.tar.gz
```
(I temporarily set the name to `faberfase` to test the fix)

I've merged my `versioneer` branch with your `parallel_rhst` before making the changes and the pr https://github.com/raamana/neuropredict/pull/15 targets this.

Before you test, try cleaning your git cache and wiping your `dist/`. Let me know how if that works.

**Comment by kevinkle** [comment]
(You may wish to squash merge afterwards... my commits are a bit of a mess)

**Comment by raamana** [comment]
Thanks Kevin, those tips helped. I will merge it tomorrow/later for you to get the credit for hacktoberfest - Cool?

**Comment by kevinkle** [comment]
Sounds good! Thanks
