### ISSUE TITLE
IO error, unable to load features

### ISSUE THREAD

**Issue by janderz8** [raamana/neuropredict#9]
Hi Pradeep,

I finally got neuropredict installed with the dependencies using python 2.7.13!  I'm having some issues with running the command, see the error message below,

Cheers,

John 

(py2713) Johns-MacBook-Pro-2:KNN John$ neuropredict -m /Users/John/Desktop/KNN/METADATAFILE.csv -o /Users/John/Desktop/KNN/features/results -u /Users/John/Desktop/KNN/features
 
Requested features for analysis:
get_dir_of_dirs from /Users/John/Desktop/KNN/features
Traceback (most recent call last):
  File "/Users/John/anaconda3/envs/py2713/lib/python2.7/site-packages/neuropredict/neuropredict.py", line 333, in getfeatures
    data, feat_names = getmethod(featdir, subjid)
  File "/Users/John/anaconda3/envs/py2713/lib/python2.7/site-packages/neuropredict/neuropredict.py", line 274, in get_dir_of_dirs
    raise IOError('Unable to load features from \n{}'.format(featfile))

**Comment by raamana** [comment]
Looks like your folder doesn't have the right format. Can you show me the output for `ls -R /Users/John/Desktop/KNN/features`

**Comment by janderz8** [comment]
I just realized the metadata file names didn't exactly match the subject folder names - it seems to be running now ... will keep you posted :)

**Comment by raamana** [comment]
Great. Try different training percentage just to be sure. Default is 50%, which can be low with small sample sizes.

[ps: i wont get notifications if you edit your previous comment, send new comments!]

**Comment by janderz8** [comment]
Good advice!  It works better with -t .95.  I only have 50 subjects, so this may be ok, I'll try .9 as well to see if I get comparable results.  Thanks again!  Cheers,

John

**Comment by raamana** [comment]
Glad to hear that. As you already can see, we need to keep in mind that these estimates are coming from small sample sizes and the performance will change (higher or lower, we don't now) on a much bigger sample..
